export default [
  {
    _id: "123",
    topic: "Space",
    userName: "SpaceX",
    handle: "@spacex",
    time: "2h",
    image: "spacex.png",
    title: "SpaceX's Mission",
    tuit: "You want to wake up in the morning and think the future is going to be great - and that’s what being a spacefaring civilization is all about. It’s about believing in the future and thinking that the future will be better than the past. And I can’t think of anything more exciting than going out there and being among the stars",
    liked: true,
    likes: 2345,
    replies: 123,
    retuits: 432,
  },
  {
    _id: "234",
    topic: "Traffic",
    userName: "The Boring Company",
    handle: "@boringcompany",
    time: "2h",
    image: "boring2.jpg",
    title: "The Boring Company fixing traffic",
    tuit: "The Boring Company (TBC) is an American infrastructure and tunnel construction services company founded by Elon Musk. Its ongoing and proposed projects are designed for intra-city ('loop') transit systems.",
    liked: true,
    likes: 2345,
    replies: 321,
    retuits: 432,
  },
  {
    _id: "345",
    topic: "Brain Injuries",
    userName: "Neurolink",
    handle: "@neurolink",
    time: "3h",
    image: "neurolink.jpg",
    title: "Neurolink fixes paralisis and blindness",
    tuit: "Neurolink is an American company founded by Elon Musk that specializes in brain to computer integration. The first application will be to cure spinal cord injuries so that paraplegics can walk again. Other applications include curing blindness and mental disorders.",
    liked: true,
    likes: 3456,
    replies: 345,
    retuits: 654,
  },
  {
    _id: 345,
    topic: "Energy",
    userName: "Tesla",
    time: "4d",
    title:
      "Tesla FSD finally makes driving obsolete. After years of delay, Tesla Full Self Driving can drive you to work while you work, play, or sleep",
    image: "tesla.png",
    liked: true,
    replies: 23,
    retuits: 45,
    likes: 777,
    handle: "@tesla",
    tuit: "Researchers from France-based pen-testing firm Synacktiv demonstrated two separate exploits against the Tesla Model 3 this week at the Pwn2Own hacking contest in Vancouver. The attacks gave them deep access into subsystems controlling the vehicle's safety and other components.",
  },
  {
    _id: 5555,
    topic: "Space",
    userName: "SpaceX",
    time: "2h",
    title:
      "100s of SpaceX Starships land on Mars after a 6 month journey. 1000s of Martian colonists being building Mars Base 1",
    image: "spacex.png",
    liked: true,
    replies: 123,
    retuits: 432,
    likes: 2345,
    handle: "@spacex",
    tuit: "You want to wake up in the morning and think the future is going to be great - and that’s what being a spacefaring civilization is all about. It’s about believing in the future and thinking that the future will be better than the past. And I can’t think of anything more exciting than going out there and being among the stars",
  },
];
